before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libopenal-dev
  - sudo apt-get install libsndfile1-dev
env:
  - RUST_TEST_TASKS=1
script:
  - ./travis_build.sh